/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://cihsevdmzzddvfgg7j7stj6fee.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vxaxqxyvqnferezaarjmz37fse",
    "aws_user_files_s3_bucket": "authcra481ecf084cd243acb55a69f1a222be7f215237-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
