/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:95fdfc3b-5f81-4626-b68a-71a051d6ee27",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ydULJLBBX",
    "aws_user_pools_web_client_id": "4j1pdb1j7j3esj593qcumpjr2b",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cihsevdmzzddvfgg7j7stj6fee.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vxaxqxyvqnferezaarjmz37fse",
    "aws_user_files_s3_bucket": "authcra481ecf084cd243acb55a69f1a222be7f215237-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
