/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://qtgt2wgfijhnzm6qi2zzpypsxi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ie4z474hujfmhlaasqbrh6wssm",
    "aws_cognito_identity_pool_id": "us-east-1:99c9904f-b7a5-4969-8b75-2e7af5d7700b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ctV3pVF6B",
    "aws_user_pools_web_client_id": "7clv61rcscs92b8i9ucujng197",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "authcra481ecf084cd243acb55a69f1a222be7f34040-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
